// Generated by CoffeeScript 1.3.3
(function() {

  define(['_'], function(_) {
    var SimulatorUtils;
    SimulatorUtils = (function() {

      function SimulatorUtils(simulator) {
        this.simulator = simulator;
        this.system = this.simulator.system;
      }

      SimulatorUtils.prototype.getNodes = function() {
        var nodes;
        nodes = [];
        this.system.eachNode(function(node) {
          return nodes.push(node.obj);
        });
        return nodes;
      };

      SimulatorUtils.prototype.getEdges = function() {
        var edges;
        edges = [];
        this.system.eachEdge(function(edge) {
          return edges.push(edge.obj);
        });
        return edges;
      };

      SimulatorUtils.prototype.removeNode = function(node) {
        var delay,
          _this = this;
        delay = this.simulator.prefs.get('delay');
        this.system.tweenNode(node.node.name, delay / 1000, {
          color: '#000',
          size: 1,
          borderWidth: 10
        });
        return _.delay(function() {
          return _this.system.pruneNode(node.node);
        }, delay / 4 * 3);
      };

      SimulatorUtils.prototype.removeEdge = function(edge) {
        return this.system.pruneEdge(edge.edge);
      };

      SimulatorUtils.prototype.isIntersectionEmpty = function(nodeSet1, nodeSet2) {
        var nodes1, nodes2;
        nodes1 = _.map(nodeSet1, function(node) {
          return node.node.name;
        });
        nodes2 = _.map(nodeSet2, function(node) {
          return node.node.name;
        });
        return _.isEmpty(_.intersection(nodes1, nodes2));
      };

      SimulatorUtils.prototype.getDegree = function(node) {
        return this.getNeighbourhood(node).length;
      };

      SimulatorUtils.prototype.getNeighbourhood = function(node) {
        var from, nodes1, nodes2, to;
        from = this.system.getEdgesFrom(node.node);
        to = this.system.getEdgesTo(node.node);
        nodes1 = _.map(from, function(edge) {
          return edge.target.obj;
        });
        nodes2 = _.map(to, function(edge) {
          return edge.source.obj;
        });
        return _.uniq(_.union(nodes1, nodes2));
      };

      return SimulatorUtils;

    })();
    return SimulatorUtils;
  });

}).call(this);
