// Generated by CoffeeScript 1.3.3
(function() {

  define(['_'], function(_) {
    var SimulatorUtils;
    SimulatorUtils = (function() {

      function SimulatorUtils(simulator) {
        this.simulator = simulator;
        this.system = this.simulator.system;
      }

      SimulatorUtils.prototype.removeNode = function(node) {
        return this.system.pruneNode(node.node);
      };

      SimulatorUtils.prototype.removeEdge = function(edge) {
        return this.system.pruneEdge(edge.edge);
      };

      SimulatorUtils.prototype.isIntersectionEmpty = function(nodeSet1, nodeSet2) {
        var nodes1, nodes2;
        nodes1 = _.map(nodeSet1, function(node) {
          return node.node.name;
        });
        nodes2 = _.map(nodeSet2, function(node) {
          return node.node.name;
        });
        return _.isEmpty(_.intersection(nodes1, nodes2));
      };

      SimulatorUtils.prototype.getNeighbourhood = function(node) {
        var from, nodes1, nodes2, to;
        from = this.system.getEdgesFrom(node.node);
        to = this.system.getEdgesTo(node.node);
        nodes1 = _.map(from, function(edge) {
          return edge.target.obj;
        });
        nodes2 = _.map(to, function(edge) {
          return edge.source.obj;
        });
        return _.uniq(_.union(nodes1, nodes2));
      };

      return SimulatorUtils;

    })();
    return SimulatorUtils;
  });

}).call(this);
